First Assessment Page
Saci-Career/saci-client pull request #4
Opened 2024-06-12 10:04 UTC by silva-00

Create a dropdown to show all roles

2024-06-13 11:26 UTC, vitorlofonseca commented on package.json
> +    "20": "^3.1.9",
What is it?

2024-06-13 11:26 UTC, vitorlofonseca commented on src/components/Divider.vue
You don't need this component, this is not being used in Figma

2024-06-13 11:28 UTC, vitorlofonseca commented on src/components/WelcomeItem.vue
What is this component? Is it being used?

2024-06-13 11:30 UTC, vitorlofonseca commented on src/stores/knowledges/actions.ts
You don't need this. The only thing related to state management you should have, is a getter to get all the Roles in the database. Just this

2024-06-13 11:31 UTC, vitorlofonseca commented on src/stores/roles/state.ts
> +const quizState = {
You don't need this

2024-06-13 11:32 UTC, vitorlofonseca commented on src/views/FirstAssessmentPage.vue
> +  <div class="container">
Classes are CapitalCasing. Can you change the classes in this file to CapitalCasing?

2024-06-13 11:33 UTC, vitorlofonseca commented on src/views/FirstAssessmentPage.vue
> +    quizActions.setSelectedRole(role)
You just need to do this in this method. Nothing more. Why you need localSelectedRole?

2024-06-13 11:33 UTC, vitorlofonseca commented on src/views/FirstAssessmentPage.vue
> +const handleRoleChange = (role: string) => {
```suggestion
const handleRoleChange = (role: Role) => {
```

2024-06-17 08:52 UTC, fromgonie requested changes
good job martin!

2024-06-17 08:52 UTC, fromgonie commented on src/stores/knowledges/index.ts
> +    removeKnowledge,
do you need all of this functions?

2024-06-17 08:52 UTC, fromgonie commented on src/stores/roles/actions.ts
> +async function addRole(role: Role): Promise<void> {
do u need this methods?

2024-06-17 08:52 UTC, fromgonie commented on src/domain/Level.ts
do you need this file? youre not using levels.

2024-06-17 10:41 UTC, vascolusitan approved these changes

2024-06-17 10:55 UTC, vitorlofonseca commented on src/components/Divider.vue
Do you need this component?

2024-06-17 10:56 UTC, vitorlofonseca commented on src/stores/quiz/actions.ts
> +  quizAnswer.value.roleId = Number(role.id)
Do you need this Number()?

2024-06-17 10:57 UTC, vitorlofonseca commented on src/stores/quiz/getters.ts
> +const quizGetters = {
A getter should always return something, and usually is a computed. Try to replicate the behaviour in other getters in admin project

2024-06-17 14:56 UTC, vitorlofonseca approved these changes

2024-06-17 17:21 UTC, vascolusitan approved these changes

2024-06-18 09:00 UTC, fromgonie approved these changes

2024-06-18 09:12 UTC, merged